#!/usr/bin/env bash
# Install HAProxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy to send traffic to web-01 and web-02
echo "frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 52.204.96.210:80 check
    server web-02 34.203.38.171:80 check" > /etc/haproxy/haproxy.cfg

# Enable HAProxy to be managed via an init script
echo "ENABLED=1" >> /etc/default/haproxy

# Restart HAProxy
service haproxy restart
