#!/usr/bin/env bash

# transfers a file from our client to a server:
# Accepts 4 parameters:
# 1. The path to the file to be transferred
# 2. The IP of the server we want to transfer the file to
# 3. The username scp connects with
# 4. The path to the SSH private key that scp uses

# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

# Check if there are less than 4 arguments provided
if [ $# -lt 4 ]
then
    # Display usage message
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # Use scp command to transfer the file to the server
    # Disable strict host key checking
    # Use the private key specified in argument 4
    # Transfer the file specified in argument 1
    # Transfer to the home directory of the user specified in argument 3
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi

